networks:
  portainer:
    name: portainer_net
    driver: bridge

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - portainer
      
volumes:
  portainer_data:
    name: portainer_data