networks:
  smtp:
    name: smtp_net
    driver: bridge

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${HOSTNAME}
    restart: unless-stopped
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
    volumes:
      - /opt/docker/dms/mail-data/:/var/mail/
      - /opt/docker/dms/mail-state/:/var/mail-state/
      - /opt/docker/dms/mail-logs/:/var/log/mail/
      - /opt/docker/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
       - DEFAULT_RELAY_HOST=[smtp-relay.gmail.com]:587
       - RELAY_USER=${RELAY_USER}
       - RELAY_PASSWORD=${RELAY_PASSWORD}
    stop_grace_period: 1m
    networks:
      - smtp